# Generated by Django 4.2.6 on 2024-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Product',
            fields=[
                ('Product_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='آیدی محصول')),
                ('Product_Code', models.CharField(default='0', max_length=10, verbose_name='کد محصول')),
                ('Product_Title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('Product_Caption', models.CharField(max_length=500, verbose_name='توضیحات محصول')),
                ('Product_Price', models.CharField(default='0', max_length=12, verbose_name='قیمت محصول')),
                ('Product_Price_Discount', models.CharField(default='0', max_length=5, verbose_name='تخفیف محصول')),
                ('Product_Image', models.ImageField(upload_to='files/Img_Product', verbose_name='عکس محصول')),
                ('Product_Type', models.CharField(max_length=20, verbose_name='نوع محصول(دست باف,ماشینی,کامپیوتری)')),
                ('Product_Date', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('Chat_Code', models.CharField(default=0, max_length=30)),
                ('user_Id', models.IntegerField(default=0, verbose_name='نام کاربری')),
                ('Product_Likes', models.IntegerField(default='0', verbose_name='علاقه مندی ها')),
                ('Product_Visit', models.IntegerField(default='0', verbose_name='بازدید')),
                ('Rate', models.CharField(default='0', max_length=15)),
                ('Product_Brand', models.CharField(default='null', max_length=20, verbose_name='برند محصول')),
                ('Product_Thread', models.CharField(default='null', max_length=20, verbose_name='جنس نخ محصول')),
                ('Product_Size', models.CharField(default='null', max_length=15, verbose_name='ابعاد محصول')),
                ('Product_Result', models.CharField(default='null', max_length=35, verbose_name='وضعیت محصول')),
                ('Product_Rag', models.CharField(default='null', max_length=5, verbose_name='رج')),
                ('Product_Shane', models.CharField(default='null', max_length=5, verbose_name='شانه')),
                ('Product_Type_Sort', models.CharField(default='null', max_length=20, verbose_name='نوع دسته دبندی(دست باف,ماشینی)')),
                ('Product_pdf_File', models.FileField(default='null', upload_to='files/file_Product', verbose_name='فایل محصول')),
                ('Product_Accss_Type', models.CharField(default='null', max_length=20, verbose_name='نوع اکسسوری')),
                ('Product_Glim_Type', models.CharField(default='null', max_length=15, verbose_name='نوع گلیم')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('Chat_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.CharField(max_length=400)),
                ('counter', models.IntegerField()),
                ('Chat_user_Id', models.IntegerField()),
                ('Chat_Code', models.CharField(default='0', max_length=30)),
                ('Chat_Message_Date', models.CharField(default='None', max_length=20)),
            ],
            options={
                'verbose_name': 'چت',
                'verbose_name_plural': 'چت ها',
            },
        ),
        migrations.CreateModel(
            name='Chats_Code',
            fields=[
                ('Chats_Code_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Chat_Code', models.CharField(default='0', max_length=30)),
            ],
            options={
                'verbose_name': 'کد چت',
                'verbose_name_plural': 'کد چت ها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('Like_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Code', models.CharField(default=0, max_length=100)),
                ('user_Id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک ها',
            },
        ),
        migrations.CreateModel(
            name='Product_Comment',
            fields=[
                ('Chat_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Chat_Code', models.CharField(default='0', max_length=30)),
                ('Product_Code', models.CharField(default='None', max_length=30)),
                ('Message', models.CharField(default='None', max_length=30)),
                ('Rate', models.CharField(default='0', max_length=15)),
                ('Date', models.CharField(default='None', max_length=20)),
                ('user_Id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'کد کامنت',
                'verbose_name_plural': 'کد کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='Product_Order',
            fields=[
                ('Product_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Code', models.CharField(default=0, max_length=100)),
                ('Product_Title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('Product_Caption', models.CharField(max_length=50, verbose_name='توضیحات محصول')),
                ('Product_Type', models.CharField(max_length=20, verbose_name='نوع محصول(دست باف,ماشینی,کامپیوتری)')),
                ('Product_Brand', models.CharField(default='None', max_length=20, verbose_name='برند محصول')),
                ('Product_Price', models.IntegerField(default='0', verbose_name='قیمت محصول')),
                ('Product_Size', models.CharField(max_length=35, verbose_name='ابعاد محصول')),
                ('Product_Result', models.CharField(max_length=35, verbose_name='وضعیت محصول')),
                ('Product_Image', models.ImageField(upload_to='', verbose_name='عکس محصول')),
                ('user_Id', models.IntegerField(default=0, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدات',
            },
        ),
        migrations.CreateModel(
            name='Seller_Genuine',
            fields=[
                ('Seller_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(default=0, max_length=11, verbose_name='شماره موبایل')),
                ('National_Code', models.CharField(default='0', max_length=10)),
                ('Cart_Number', models.CharField(default='0', max_length=16)),
                ('Shaba_Number', models.CharField(default='0', max_length=24)),
                ('Shop_Name', models.CharField(default='None', max_length=20)),
                ('Seller_IpAddress', models.CharField(default='None', max_length=30)),
                ('password', models.CharField(default='None', max_length=20, verbose_name='گذرواژه')),
            ],
            options={
                'verbose_name': 'فروشنده حقیقی',
                'verbose_name_plural': 'فروشنده های حقیقی',
            },
        ),
        migrations.CreateModel(
            name='Seller_Legal',
            fields=[
                ('Seller_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(default=0, max_length=11, verbose_name='شماره موبایل')),
                ('Company_Name', models.CharField(default='None', max_length=30)),
                ('Company_Type', models.CharField(default='None', max_length=30)),
                ('Company_National_Code', models.CharField(default='0', max_length=10)),
                ('Economic_Code_Company', models.CharField(default='0', max_length=24)),
                ('Shaba_number', models.CharField(default='0', max_length=24)),
                ('Signatory', models.CharField(default='None', max_length=40)),
                ('Shop_Name', models.CharField(default='None', max_length=30)),
                ('Seller_IpAddress', models.CharField(default='None', max_length=30)),
                ('password', models.CharField(default='None', max_length=20, verbose_name='گذرواژه')),
            ],
            options={
                'verbose_name': 'فروشنده حقوقی',
                'verbose_name_plural': 'فروشنده های حقوقی',
            },
        ),
        migrations.CreateModel(
            name='User_Save',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('family', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(default=0, max_length=10, verbose_name='کد ملی')),
                ('date_of_birth', models.CharField(default='None', max_length=10, verbose_name='تاریخ تولد')),
                ('Phone', models.IntegerField(default=0, verbose_name='شماره موبایل')),
                ('Email', models.EmailField(max_length=30, verbose_name='ایمیل')),
                ('job', models.CharField(default='None', max_length=30, verbose_name='شغل')),
                ('redirect', models.CharField(default='None', max_length=20, verbose_name='روش برگرداندن پول')),
                ('UserName', models.CharField(max_length=30, verbose_name='نام کاربری')),
                ('password', models.CharField(default='None', max_length=20, verbose_name='گذرواژه')),
                ('repassword', models.CharField(default='None', max_length=20, verbose_name='تکرار گذرواژه')),
                ('Rol', models.CharField(default='None', max_length=20, verbose_name='رول')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب ها',
            },
        ),
        migrations.CreateModel(
            name='User_View',
            fields=[
                ('View_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Code', models.CharField(default=0, max_length=100)),
                ('user_Id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدید ها',
            },
        ),
    ]
