# Generated by Django 4.2.6 on 2024-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='Product_Price_Final',
            field=models.CharField(default='0', max_length=12, verbose_name='قیمت نهایی محصول'),
        ),
    ]
