# Generated by Django 4.2.6 on 2024-06-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_add_product_product_price_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='Product_Un_Type_Sort',
            field=models.CharField(default='null', max_length=20, verbose_name='نوع دسته بندی'),
        ),
    ]
