# Generated by Django 4.2.6 on 2024-06-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_add_product_product_un_type_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('family', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(default=0, max_length=10, verbose_name='کد ملی')),
                ('date_of_birth', models.CharField(default='None', max_length=10, verbose_name='تاریخ تولد')),
                ('Phone', models.IntegerField(default=0, verbose_name='شماره موبایل')),
                ('Email', models.EmailField(max_length=30, verbose_name='ایمیل')),
                ('job', models.CharField(default='None', max_length=30, verbose_name='شغل')),
                ('redirect', models.CharField(default='None', max_length=20, verbose_name='روش برگرداندن پول')),
                ('UserName', models.CharField(max_length=30, verbose_name='نام کاربری')),
                ('password', models.CharField(default='None', max_length=20, verbose_name='گذرواژه')),
                ('repassword', models.CharField(default='None', max_length=20, verbose_name='تکرار گذرواژه')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_save',
            name='Rol',
        ),
    ]
