# Generated by Django 4.2.6 on 2024-06-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_supporter_remove_user_save_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='Chat_Code',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
