# Generated by Django 4.2.6 on 2024-06-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_chats_chat_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='Chat_Owner',
            new_name='Chat_user2_Id',
        ),
    ]
