# Generated by Django 4.2.6 on 2024-06-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_rename_chat_owner_chats_chat_user2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='Seender',
            field=models.IntegerField(default='0'),
        ),
    ]
