# Generated by Django 4.2.6 on 2024-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_chats_seender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='With',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
