# Generated by Django 4.2.6 on 2024-06-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_seller_genuine_state_seller_legal_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='files/Img_Product', verbose_name='عکس محصول'),
        ),
    ]
