# Generated by Django 4.2.6 on 2024-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_alter_add_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Product_Date',
            field=models.CharField(max_length=30, verbose_name='تاریخ انتشار'),
        ),
    ]
