# Generated by Django 4.2.6 on 2024-08-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_add_product_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Complete',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.CharField(max_length=30, verbose_name='قیمت')),
                ('user_Id', models.IntegerField(verbose_name='')),
                ('Date', models.CharField(default='None', max_length=30, verbose_name='')),
                ('Order_Code', models.CharField(max_length=10, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='Date',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='product_order',
            name='Order_Code',
            field=models.CharField(default=0, max_length=10, verbose_name=''),
        ),
        migrations.AddField(
            model_name='user_view',
            name='Date',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Product_Caption',
            field=models.CharField(max_length=1000, verbose_name='توضیحات محصول'),
        ),
    ]
