# Generated by Django 4.2.6 on 2024-08-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_order_complete_like_date_product_order_order_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_buyed',
            fields=[
                ('Product_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Code', models.CharField(default=0, max_length=100)),
                ('Date', models.CharField(default='None', max_length=30, verbose_name='')),
                ('user_Id', models.IntegerField(default=0, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدات',
            },
        ),
    ]
